version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  go112:
    docker:
      - image: circleci/golang:1.12.7
        environment:
          HTTPBIN_URL: http://httpbin.org
      - image: kennethreitz/httpbin
        name: httpbin.org

    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go test -i ./...
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"
      - run: go test ./... -coverprofile=/tmp/coverprofile -covermode=atomic
      - codecov/upload:
          file: /tmp/coverprofile

workflows:
  version: 2
  default:
    jobs:
      - go112
